### ISSUE TITLE
Print double

### ISSUE THREAD

**Issue by xiaohe27** [kframework/java-semantics#45]
Just a reminder for myself that additional tests for toString(Float) are needed to ensure it outputs the same string as Java does.
1. Inside range [10^-3, 10^7), the string is in normal decimal notation: integer part and fractional part are separated by a decimal point ".", where the fractional part is at least one digit.
2. If the double number is outside of the above range, then it is in scientific notation.
3. Special cases like Nan, Infinity etc.

**Comment by bmmoore** [comment]
`java.lang.Float` has some useful stuff for calculating reference results. including `floatToRawIntBits` and `intToFloatBits` that can be used to find the next float larger or smaller than a given float. The largest value less than `0.001` prints as `9.999999E-4`, and the least number larger than `9999999.0` prints as `1.0E7`.

**Comment by xiaohe27** [comment]
@bmmoore  Thank you for the advice.
