### ISSUE TITLE
kjkompile.sh error

### ISSUE THREAD

**Issue by imran-iitp** [kframework/java-semantics#56]
I have completed all the steps required for Installation.
I am getting following error while compiling Java-Semantics as per the details given in README.md(~/java-sematics):
****************************************************
Preprocessing semantics:
[Error] Compiler: Could not find sorts: [Exp]
	Source(/home/iitp/java-semantics/src/./prep/../common/list-syntax.k)
	Location(38,38,38,99)

Execution semantics:
[Error] Critical: Could not find file: builtins/model-checker.k
Lookup directories:[./exec, /home/iitp/k/lib/java/../../include/builtin]
	Source(/home/iitp/java-semantics/src/./exec/ltl-support.k)
	Location(1,1,1,34)
********************************************************
Please help me out to solve this problem.....

**Comment by laurayuwen** [comment]
K is upgrading at the moment, so latest version not supporting Java semantics. Please use this version: https://github.com/kframework/k/tree/javaCompatible, I updated Readme, thanks!

**Comment by imran-iitp** [comment]
Thank You sir..
